const customAuctionIcons = {
    "Engelschuhe v3": "https://i.postimg.cc/jSnGfbHW/engelsschuhe-v2.png",
    "Unendliche Kohle": "https://i.postimg.cc/9QHBxH3Z/unendliche-kohle.png",
    "Dorfbewohner Talisman": "https://i.postimg.cc/N0JJCC73/Dorfbewohner-talisman.png",
    "Magnet": "https://i.postimg.cc/mg6C0vJd/magnet.png",
    "Thanos Handschuh": "https://i.postimg.cc/PJ2P1ZkS/Thanos-handschuh.png",
    "+20% Speed Upgrade Modul": "https://i.postimg.cc/TYsPGT2T/20-speed.png",
    "+120% Speed Upgrade Modul": "https://i.postimg.cc/DyS2xRQn/120-speed-Upgrade-Modul.png",
    "Mini Pilzaxt": "https://i.postimg.cc/Gpdtgqhs/e.png",
    "Mini One Hit Wonder": "https://i.postimg.cc/g0gzSp7L/mini-One-hit-wonder.png",
    "Talismanrucksack": "https://i.postimg.cc/8zHfSqYZ/grosser-talismann-rucksack.png",
    "Mini Obsihacke": "https://i.postimg.cc/zG0vMTL9/Mini-o-BSIHACKE.png",
    "Wasserwaage": "https://i.postimg.cc/Y0zMFwYD/Wasserwage.png",
    "Runenbrecher": "https://i.postimg.cc/bY9h3pSF/Runenbrecher.png",
    "Kleiner Talismanrucksack": "https://i.postimg.cc/50twTxNn/kleiner-talismanrucksack.png",
    "Superball": "https://i.postimg.cc/nrgNSFBC/Superball.png",
    "Jagdmesser": "https://i.postimg.cc/QtbfWX0y/jagdmesser.png",
    "x Will´s Bauhacke x": "https://i.postimg.cc/wTtnnmWL/wills-Bauhacke.png",
    "Phils Kristallkrone": "https://i.postimg.cc/6qZg4s4d/phils-kristallkrone.png",
    "OP Teppichmesser": "https://i.postimg.cc/kgqzGpJj/OP-teppichmesser.png",
    "Riesenpilz": "https://i.postimg.cc/26sXDH9h/Riesenpilz.png",
    "Zwergenpilz": "https://i.postimg.cc/nhFSp92D/zwergenpilz.png",
    "Poseidon's Talisman": "https://i.postimg.cc/C54CQJWr/POSEIDONS-TALISMAN.png",
    "DJ NPC": "https://i.postimg.cc/sXdpftyz/kkkkge.png",
    "Yamakuza Roller": "https://i.postimg.cc/HnW8VmNT/Yamakuza-Roller.png",
    "Lotterieschwingen": "https://i.postimg.cc/dtxZtzjP/Lotteri.png",
    "OP Aktenkoffer": "https://i.postimg.cc/FRkNpBJK/OP-koffer.png",
    "OP Jet": "https://i.postimg.cc/6QyX6mcc/OP-Jet.png",
    "PARTY-Jetpack": "https://i.postimg.cc/XvTTj7pq/party-jetpack.png",
    "Emmys Videokamera": "https://i.postimg.cc/k4Qh7Q0S/Emmys-videokamara.png",
    "Jetpack": "https://i.postimg.cc/SNT1QNPy/jetpack.png",
    "Runenspitzhacke": "https://i.postimg.cc/G2xzWcYm/Runenspitzhacke.png",
    "Poseidons Angel": "https://i.postimg.cc/Vs4D4kmr/Poseidons-angel.png",
    "Schmelzpicke v3": "https://i.postimg.cc/ryhNxZNt/schmelzpicke-v3.png",
    "Motocross OP 690": "https://i.postimg.cc/G2XGP9Gd/Motocross-OP-690.png",
    "Philips Anzughose": "https://i.postimg.cc/JzjX6pjw/anzug-hose.png",
    "Philips Anzugschuhe": "https://i.postimg.cc/D0tW5Gz9/anzug-shuhe.png",
    "Philips Jackett": "https://i.postimg.cc/c1KB7Mks/anzug-brusplatte.png",
    "Philips Brille": "https://i.postimg.cc/Fs53ytJ9/anzug-helm.png",
    "Phils geheime Freundin": "https://i.postimg.cc/QCL9J5V3/phils-freundin.png",
    "Erdspalter-Schaufel": "https://i.postimg.cc/mkND350j/Erdspalter-schaufel.png",
    "Engelshemd": "https://i.postimg.cc/QtMGYn9C/Engelshemd.png",
    "Engelshose": "https://i.postimg.cc/nrj8pj1c/Engelshose.png",
    "Engelshelm": "https://i.postimg.cc/PfgfNT8t/engelshelm.png",
    "ADMIN Banhammer": "https://i.postimg.cc/Kv5XF2Pg/ADMIN-Banhammer.png",
    "Emmys Herzstab": "https://i.postimg.cc/fTqKYqD4/Emmys-Herzstab.png",
    "Motorsense": "https://i.postimg.cc/XJWcnTcq/Motorsense.png",
    "Builder Axt": "https://i.postimg.cc/2y8QZhth/Builder-Axt.png",
    "Stab des Nekromanten": "https://i.postimg.cc/d1QkHvjH/Stab-des-Nekromanten.png",
    "Sculkschaufel": "https://i.postimg.cc/VvrNpNrZ/Sculkschaufel.png",
    "Sculkhelm": "https://i.postimg.cc/FzLLcpZF/sculkhelm.png",
    "Sculkbrustplatte": "https://i.postimg.cc/qvdF5Mzb/sculkbrustplatte.png",
    "Sculkbogen": "https://i.postimg.cc/vmYNGq71/Sculkbogen.png",
    "Schneeballkanone": "https://i.postimg.cc/9f0YxvtY/Schneeballkanone.png",
    "Plüsch Emmy": "https://i.postimg.cc/BQC5Jqm1/Plusch-Emmy.png",
    "Plüsch elasino": "https://i.postimg.cc/0jsmq3mY/Plusch-elasino.png",
    "Plüsch Flink": "https://i.postimg.cc/d1HPMMzP/Plusch-Flink.png",
    "Plüsch oopslee ": "https://i.postimg.cc/cCvq09SF/Pluschi-oopslee.png",
    "Flammentalisman": "https://i.postimg.cc/4dFML691/Flammentalisman.png",
    "Furious Skyline": "https://i.postimg.cc/RFn8Y3Qd/Furious-Skyline.png",
    "Minion-Axt": "https://i.postimg.cc/mDQjM7SL/minon-axt.png",
    "Oxidtalisman": "https://i.postimg.cc/90LGtbRK/oxidations-talisman.png",
    "Gräbergemisch": "https://i.postimg.cc/x8Jt4M99/grabergemisch.png",
    "Holzbündel": "https://i.postimg.cc/yY9zJS0W/holz-gemisch.png",
    "OPSUCHT Kaffeetasse": "https://i.postimg.cc/GpKDdVHd/OPSUCHT-kafetasse.png",
    "OP-City": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "OP Pass": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "OP Bank": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "OP-Kiste": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Playbutton": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Supporter-Team": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Luxury Island": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Kristalle": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Builder-Team": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "1. EDITION Boosterpack": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Filmstudio": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Farmwelt": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Content-Team": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Mod-Team": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "ByteException_ Sammelkarte": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Marktplatz": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Immobilienmarkt": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Tresor": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "OP Minion": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Auktionshaus": "https://i.postimg.cc/d1K5xLLB/1-edition-boosterpack.png",
    "Mini-Bohrer": "https://i.postimg.cc/4NbH6nTL/mini-Bohrer.png",
    "+60% Speed Upgrade Modul": "https://i.postimg.cc/8PDjzDr9/speed-upgrade-tamplate.png",
    "Gletscherschaufel": "https://i.postimg.cc/T1n0qGRq/fhdfxghfghage.png",
    "Gletscheraxt": "https://i.postimg.cc/Yqwb24Rw/Gletscheraxt.png",
    "Gletscherhelm": "https://i.postimg.cc/rF8xY5gs/Gletscherhelm.png",
    "Gletscherstiefel": "https://i.postimg.cc/K8WTzwb7/Gletscherschuhe.png",
    "Gletscherhose": "https://i.postimg.cc/J7QBJGmz/Gletscherhose.png",
    "Träumerschaufel": "https://i.postimg.cc/RVFqHdX6/Traumerschaufel.png",
    "Osterhasen Schuhe V2": "https://i.postimg.cc/j2kxcVZf/Osterhasen-schuhe-v2.png",
    "Geschenkbrustplatte": "https://i.postimg.cc/zf1J0FS0/Gletscher-brustplatte.png",
    "Marcels Adminhelm": "https://i.postimg.cc/bNB0Ds0M/Marcels-Adminhelm.png",
    "Kleiner Beschützer Phil": "https://i.postimg.cc/ZK23YX45/Kleiner-Beschutzer-Phil.png",
    "Propellerhut": "https://i.postimg.cc/hGqdTxJS/Propellerhut.png",
    "Kleiner Beschützer Marcel": "https://i.postimg.cc/B6SPw0cR/Kleiner-Beschutzer-Marcel.png",
    "X Will's Helm X": "https://i.postimg.cc/4ND7RtQP/wills-helm.png",
    "X Will's Stiefel X": "https://i.postimg.cc/dQXDGdpc/wills-stiefel.png",
    "Glowstone | Schneider": "https://i.postimg.cc/6TJ9gVx2/Glow-stone-schneider.png",
    "XP Talisman": "https://i.postimg.cc/Nfq9Wm4M/XP-Talisman.png",
    "Marcels Adminstiefel": "https://i.postimg.cc/k5bd36wF/marcels-adminstiefel.png",
    "Black Flügel": "https://i.postimg.cc/HskNQcqt/Black-Flugel.png",
    "H4CKER.exe": {
      "LEATHER_HELMET": "https://i.postimg.cc/3NFnm31q/hacker-helm.png",
      "LEATHER_CHESTPLATE": "https://i.postimg.cc/CLJcKLzj/hacker-brustplatte.png",
      "LEATHER_LEGGINGS": "https://i.postimg.cc/L8DF2pph/hackerleggings.png",
      "LEATHER_BOOTS": "https://i.postimg.cc/rmSJ2qB0/Hacker-schuhe.png"
    }
  };
