name: Save Shard Price History

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

concurrency:
  group: save-shard-history
  cancel-in-progress: false

jobs:
  save_history:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios firebase-admin

      - name: Run script to save shard history
        run: node ./fetch-shards.js
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}

      - name: Commit and push shard history file
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

          git add shard-history.json

          if git diff --staged --quiet; then
            echo "Keine Änderungen vorhanden."
            exit 0
          fi

          git commit -m "Update shard-history.json"

          git fetch origin main
          git rebase origin/main

          git push origin main
